### ISSUE TITLE
📌 2nd Iteration Dev Checklist

### ISSUE THREAD

**Issue by KaiserZZK** [KaiserZZK/Adv-sWE-SOME#49]
**- Client [5 pts]**
  - [x] Did they develop a demoable client that exercises a reasonable subset of their API and does the README document how to build the client and run the client together with their service?

**- Multiple Client Instances [10 pts]**
  - [x] Does their  service support multiple simultaneous instances of the sample client?  
  - [x] Can the service tell them apart? Can the service handle multiple requests/responses from different client instances in parallel and track which requests involving which data came from which client (and send  corresponding responses only to the appropriate clients)? 
  - [x] Does the test  suite for the service include tests that check that the service indeed  operates properly when it has multiple concurrent clients? 

**- Continuous Integration [5 pts]**
  - [x] Does the main repo perform CI such that all following tools are automatically run for every commit to the main branch of the codebase (or on a schedule such as nightly)? 
    - [x] build (`./mvnw clean install`)
    - [x] analysis (static analysis with Stylecheck, `./mvnw checkstyle:check`)
    - [x] testing (`./mvnw test`) 
  - [x] Are the CI reports in the repo or  linked from the repo? (available in `./reports/`)

**- Internal Integration Tests [5 pts]**
  - [x] Does the codebase include integration tests for the components of the service code that run automatically during CI?
 
**- Branch Coverage [5 pts]**
  - [x] Did the team  run branch coverage during automated testing? Does the repo contain or  link to coverage reports? 
  - [x] Is the branch coverage at least 85%? If 85%  was not achieved, is there some explanation why not in the README or elsewhere in the repo? 

**- Bug Finder [5 pts]**
  - [x] Did the team  run a static analysis 'bug finder' tool on their entire codebase (except  for any third-party code)? 
  - [x] Does it run automatically during CI? Are bug  finder reports included in or linked from the repo?

**- End-to-End Testing [6 pts]**
  - [x] Is there  reasonable evidence that the team did substantial end-to-end testing of  their client utilizing their service? It's ok if these tests are manual,  but there should be a written checklist or some other mechanism that  makes it easier to redo the exact same tests multiple times. 

This criterion is linked to a Learning Outcome                  Third Party Code                             Do they  document all third-party code used, whether library, API, database,  etc., where it is in the repo (if applicable), and where they got it  from (e.g., link to download or documentation)? |   | 1 pts
This criterion is linked to a Learning Outcome                  API Documentation                             Has their API documentation been updated to the 'final' version of their service? |   | 1 pts
This criterion is linked to a Learning Outcome                  Configuration                             Is sufficient  documentation included in the repo to enable an arbitrary developer (who  already knows their programming language and its ecosystem) to build,  run and test their service? Are all necessary configuration files  included in the repo? |   | 1 pts
This criterion is linked to a Learning Outcome                  Client Target Audience                             Does the client provide what seems like reasonable functionality for one or more of the designated target audiences? |   | 3 pts
This criterion is linked to a Learning Outcome                  External Integration Tests                             Are there  tests for checking the interfaces to any third-party libraries and  services used? Are there tests checking the interfaces to all  environmental or external resources such as files and databases? |   | 3 pts
